import "../styles/globals.css";
import { Html, Head} from 'next/document
import Transition from "../components/Transition";

import Layout from "../components/Layout";
// next router js
import { useRouter } from "next/router";
// framer Motion
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { AnimatePresence, motion } from "framer-motion";
function MyApp({ Component, pageProps }) {
  const router = useRouter();
  return (
   <Html>
      <Head>
        <link rel='shortcut icon' href'https://awash.netlify.app/logo.png'/>
    
      </Head>
    <body>
       <Layout>
      <AnimatePresence mode="wait">
        <motion.div key={router.route} className="h-full">
          <Transition />
          <Component {...pageProps} />
        </motion.div>
      </AnimatePresence>
    </Layout>
    </body>
    </Html>
  );
}

export default MyApp;
